### ISSUE TITLE
Task assumes large concourse workers

### ISSUE THREAD

**Issue by johannaratliff** [cloudfoundry/cats-concourse-task#9]
The task defaults to run across [12 nodes](https://github.com/cloudfoundry/cats-concourse-task/blob/bdc220fb869a75b4a5eec84ec3abf2c83ac8a4d8/task.yml#L20). This assumes a very large concourse worker. Our concourse workers are [n1-standard-8s](https://cloud.google.com/compute/docs/machine-types) and fail CATs >90% by default use of this task. By scaling down to 9 nodes on our task against 6 n1-standard-8 workers, we get a significantly higher pass rate on CATs.

I would like to see documentation surrounding the need to configure number of nodes against an average machine size.

**Comment by dsabeti** [comment]
Hi @JohannaSmith. It looks like we're using n1-highcpu-16 for our concourse workers, which enables us to use 12 ginkgo nodes.

One thing that makes this a bit annoying is that there isn't really a notion of an "average" machine size -- plenty of teams using n1-standard-8, n1-standard-4, as well as various types in the n1-highcpu family. We can only hope to do a best effort in documenting the number of nodes to use for a given machine size. A simple way to do this might be to just ask teams that are already using the task for what they've found. For example, the README could include a table like this:

| Num CPUs | GCP VM Type (as an example) | Recommended Gingko nodes |
| ----------- | ------------------------------ | ----------------------------- |
| 16 | n1-highcpu-16 | 12 |
| 8 | n1-highcpu-8 | 9 |
| 4 | n1-highcpu-4 | 6 |

Does that seem like a reasonable way to document this?

Also, just in general, I'd recommend a different approach to Concourse workers. Instead of having many smaller workers, we've found that we prefer just a few larger workers -- partially so that we can run tests this way, but also because we've found that CPU is almost always the bottleneck resource (as opposed to memory) and we can optimize for that by using the highcpu series.

**Comment by davewalter** [comment]
Closing issue since repo has been archived.
